### ISSUE TITLE
config directory is not created on first launch

### ISSUE THREAD

**Issue by elig0n** [emonkak/geektray#1]
on first launch directory $HOME/.config/geektray is not created when not existing so configuration file cannot be written to

```
Error: write config file

Caused by:
    No such file or directory (os error 2)
```

so I had to manually create it

**Comment by emonkak** [comment]
This is fixed in https://github.com/emonkak/geektray/commit/fdfb3d198f30ead408cf5225620d32322e2772f1. Thanks for the report.
